### ISSUE TITLE
Are expressions always effectively INST?

### ISSUE THREAD

**Issue by PuppyPi** [Creatures-Developer-Network/c2e-quirks#24]
Is it okay if a caos *expression* (though not script) executes atomically (like it's in INST mode) outside of official INST mode?
Like if you have 'sets va00 read game "foo" cati fmly gnus tint 4'  (that's a contrived example XD' )
Does that have to be interruptible (like stopped before it does the "read" function but after it does the "game" function), does it have to be run like they're in an inst, or can it go either way?

(If the original engine evaluates expressions atomically, it might explain why the CAOS dynamic evaluation command always runs in an INST mode! and why ADDV/MULV/etc. are statements not expressions—to encourage code to be broken up into more statements to help it be interruptible!)

**Comment by Vermidia** [comment]
Wouldn't really know how to test this, but using just the caos command line/(install script probably works too), 
targ pntr sets va00 read game "Poker" cati fmly gnus 0 outs va00 will correctly produce "decision"

**Comment by PuppyPi** [comment]
Aha I know how to test it :3

Include two non-command functions with side effects in the same statement, like PRAY INJT (which returns an int) and CAOS (which returns a string) given some code that does something and combine them like, idk, as parameters to the TINT or READ command or something idk XD
(or it could be two CAOS commands, one which is given code that sets one NAME variable, another that sets another X3 )

Then try interrupting that script a bajillion times like crazy (natural scheduling interruptions but also maybe with MESG, STPT, KILL, etc.!) and see if it ever ever happens that one of those CAOS functions executes but not the other one :3

Aha here's an example I think would work!  :D

*outside of inst and lock obviously!
targ ownr
prt: onew 1     caos 1 1 0 0 "setv mame \"a\" 1" 1 0 va99       caos 1 1 0 0 "setv mame \"b\" 1" 1 0 va99     0 0

And then you make a bajillion of those agents and try your absolute best to obliterate them or otherwise get the checker script to in between one setting mame "a" and setting mame "b", so that if even a single time ever an agent exists with its "a" name var set but not its "b" var, then we know CAOS Statements are interruptible :3

if they are, then we still need to check that expressions are interruptible!
Here's an example single expression tree that could probably be interrupted!  (if that's possible)

targ ownr
setv va00   sins   caos 1 1 0 0 "setv mame \"a\" 1" 1 0 va99       0     caos 1 1 0 0 "setv mame \"b\" 1" 1 0 va99


(also, obviously KILLing it would not be useful in that way of doing it XD, but you could set GAME/EAME variables instead and then killing it would be okay but you could only do one such agent at a time..which maybe is a good thing anyway idk!)

(Note that the script which checks for these variables should either be inst or should check "a" before checking "b", otherwise it might see "b" as absent (then the agent sets both its vars) then see "a" as present, giving a false positive!  :3 )

(And to be sure, you don't have to obliterate kill/stop/mesg/etc. the agent XD just being "interrupted" naturally by the scheduler would be fine! (particularly if the checker checks for the presence of the two variables while in inst mode, itself) but using stpt/kill/etc. is another way to try and trigger that happening :3 )

(It might also be the case that this script is just too short to be interrupted but longer ones would!  Maybe add some big things like a reps 1000 or enum 0 0 0 or net: ruso or something into the scripts alongside setv mame "foo" 1, to make them take longer to increase the chances and interruption between them will occur :3 )

If you or anyone reading this has any questions (eg, because I'm not making sense), feel free to ask XD''

**Comment by Vermidia** [comment]
Well
AHE0001: Attempt to access NULL handle
It doesn't want to let me do any CAOS commands for the prt: onew it seems
Even caos 1 1 0 0 "setv va00 1" 1 0 va99 calls this error :p
Will try the setv thing instead

**Comment by Vermidia** [comment]
So I've tried
``
inst
setv name 2 0
setv name 1 0
slow
wait 5
setv va00 sins caos 1 1 0 0 " setv va01 2 setv mame va01 1" 1 0 va99 0 caos 1 1 0 0 "setv va00 1 setv mame va00 1" 1 0 va99
``
with an interrupting script of
``
reps 1000
	rtar 1 2 3000
	inst
	stpt
	doif name 1 ne name 2
		dbg: outs "Listening:"
		dbg: outv name 1
		dbg: outv name 2
	endi
	slow
repe
``
And I couldn't get it to ever get name 1 != name 2

**Comment by PuppyPi** [comment]
Awesome!  That's a better script than the one I wrote!  :D

(And ooooooooh golly I forgot NAME var keys can be anything not just strings like GAME/EAME—that's important not to forget! XD'' )

I guess we'll close this for now and go on the assumption that both expressions and statements aren't interruptible and if anyone ever can pull it off then we can reopen it :3

(It makes sense to me that they wouldn't be—that explains a lot about the design of caos like I mentioned in the OP!)
(And now that I'm writing an engine impl myself I can definitely see how it's easier to make each statement (and thus definitely each expression) atomic, with recursive interpreter functions written in a normal uninterruptible language like C or Java, or similar!  XD )

**Comment by PuppyPi** [comment]
Haha here's even more support for this!:

In the docs for NET: RUSO
> This is a command rather than an integer r-value because it is blocking.
