### ISSUE TITLE
Was the angular physics engine ever implemented in C2E?  (SPIN/ROTN/AVEL and Rotatable/Presence ATTR flags and Script 8 )

### ISSUE THREAD

**Issue by PuppyPi** [Creatures-Developer-Network/c2e-quirks#28]
Was the angular physics engine ever implemented in C2E? XD
(ie, SPIN/ROTN/AVEL and Rotatable/Presence ATTR flags and Script 8 )

**Comment by Vermidia** [comment]
In CV and C3/DS, no. Not sure about Sea Monkeys.

**Comment by PuppyPi** [comment]
Haha they got too big for their britches then XD
Okie thanks :>
