### ISSUE TITLE
What happens when CALL/MESG/etc. uses an event number for which there isn't a script in the scriptorium for that family/genus/species?

### ISSUE THREAD

**Issue by PuppyPi** [Creatures-Developer-Network/c2e-quirks#29]
What happens when CALL/MESG/etc. uses an event number for which there isn't a script in the scriptorium for that family/genus/species?

**Comment by Vermidia** [comment]
Tested MESG, nothing seems to happen.

**Comment by Vermidia** [comment]
CALL doesn't error out and completes the rest of the CALLer script anyway.

**Comment by PuppyPi** [comment]
Thanks!  :D
