### ISSUE TITLE
If STOP/STPT is invoked during a CALLed script, does that stop the caller script as well, or immediately return back to it?

### ISSUE THREAD

**Issue by PuppyPi** [Creatures-Developer-Network/c2e-quirks#30]
If STOP (or STPT with TARG OWNR) is invoked during a CALLed script, does that stop the caller script as well, or just stop the CALLed script and immediately return back to the line after "CALL" in the caller like it exited normally?

**Comment by Vermidia** [comment]
STOP stops the CALLed script but does return back to the line in the caller script after call like it exited normally, but STPT(On the same agent) stops the CALLed script and the caller script.

**Comment by PuppyPi** [comment]
Thanks!
By "STOP stops the caller script" did you mean "STOP stops the call**ed** script" or no?

**Comment by Vermidia** [comment]
Yeah, that was a typo, it stops the called script but not the caller script

**Comment by PuppyPi** [comment]
Awesome!  :DD
(That subsumes my other question about a RETN for the whole script—it's STOP!  :D )
(So I didn't make an Issue for that one :3 )
