### ISSUE TITLE
Can PAUS OWNR be done or does that throw an error?

### ISSUE THREAD

**Issue by PuppyPi** [Creatures-Developer-Network/c2e-quirks#32]
Can PAUS'ing OWNR be done or does that throw an error?
That is, to be exact, "PAUS 1" while TARG is OWNR

And if so, does that mean it always gets itself stuck on that line of code and some other script (another agent or the CAOS tool external program perhaps or etc.) has to unpause it?

**Comment by Vermidia** [comment]
Paus 1 while on ownr does pause the agent. Weirdly, testing it out, (No inst), the script did complete itself, but after that the agent completely stopped in it's tracks and no longer ticked(was using a timed agent for this one). It does require a seperate agent to unpause it.

**Comment by PuppyPi** [comment]
Oh that's fascinating!  Even not in INST!
That's very interesting!  I suppose the engine only reads the PAUS state when *starting* an event script!  :D

**Comment by PuppyPi** [comment]
Oh what about current-script vs. whole-call-stack?

"the script did complete itself" if it was a CALLed script, did it wait for just that script to finish, or wait for the whole CALL stack to finish and the Agent VM to become quiescent again?

**Comment by Vermidia** [comment]
Depends on inst it seems. If the 2 scripts can complete in a tick they'll run without interruption, but if the CALLed script takes to long, the CALLer won't finish, and if the CALLer needs more than a tick to finish(and PAUSed before) it won't ever get to the CALL command.

I assume this applies to my previous test as well, it was just short enough to be consistent. Yep, if the main script needs more than a tick byitself, it will fail to complete.

**Comment by PuppyPi** [comment]
Wait, so you're saying if does PAUS 1 to itself, then does stuff, then does CALL, that if that stuff takes too long, it won't get to the CALL command to even start the CALLed script?  (unless something external to itself unPAUSes it ofc)

(Which, if true, would apply to anything after the PAUS?  Not just CALL?  And be the total opposite of what we thought before? XD )

**Comment by Vermidia** [comment]
Anything after the PAUS 1 yes, it has to finish it in that tick I guess? Otherwise it can't finish itself.

**Comment by PuppyPi** [comment]
Ahaaaaaaaa!  So it _is_ that way!
Thanks so much!
I'll revert things I did based on the previous perception XD
