### ISSUE TITLE
Can CAOS functions be used as CAOS commands?

### ISSUE THREAD

**Issue by PuppyPi** [Creatures-Developer-Network/c2e-quirks#36]
Can you just use a CAOS function that returns a value as if it didn't? XD   (eg, just run the "CAOS" function and discard its return value / pretend it didn't have one)

(Namely use the CAOS or PRAY INJT *function* like it was a command or do you have to prepend a "SETV va00 " or something similar to capture the return value and just not use it?)

**Comment by Amaikokonut** [comment]
The latter-- since CAOS is technically classed as a string and not a command (and PRAY INJT is classed as an integer) they need to be sets/setv or the engine complains 'invalid command' (is that what you're asking?)

**Comment by PuppyPi** [comment]
Yes that's exactly it!  Thanks!  :D
