### ISSUE TITLE
What happens when a camera views another camera's viewscreen?

### ISSUE THREAD

**Issue by PuppyPi** [Creatures-Developer-Network/c2e-quirks#40]
Does it:
• Show a blank screen for all cameras?  (My memory tells me this is it, but I'm not totally sure)
• Show a blank screen for only itself?  (What happens on cycles, then?  Like A looking at B looking at A?  XD )
• Something else?

**Comment by PuppyPi** [comment]
Oh and by "blank screen" is that just:  It doesn't display the viewscreen at all and viewscreen-holding agents are just expected to have a proper blank screen looking thing in their sprite that's normally covered up by the viewscreen?

**Comment by Vermidia** [comment]
[GIF of it](https://gyazo.com/6ef61dc209d56aeeca5290e05d109fe3)
Basically: All the camera screens it shows are blank.

**Comment by PuppyPi** [comment]
Aha thanks!  :D
