### ISSUE TITLE
Err'd scripts and the CALL stack

### ISSUE THREAD

**Issue by PuppyPi** [Creatures-Developer-Network/c2e-quirks#41]
When a script causes an error (and you don't do Brutal Ignore XD ), if it was a CALLed script that gets stopped, does that stop the CALLer as well (and its CALLer if present and its CALLer and etc.)?

**Comment by Vermidia** [comment]
It does stop the CALLer of a CALLed script, and also stops the CALLer of the CALLer.(Tested with stop script error option)

**Comment by PuppyPi** [comment]
Thanks!  :D
