### ISSUE TITLE
Does STOP and TARG OWNR STPT work in INST mode?

### ISSUE THREAD

**Issue by PuppyPi** [Creatures-Developer-Network/c2e-quirks#44]
So Verm says that STOP stops only the current script in the CALL stack while STPT (while TARG = OWNR) stops the entire CALL stack.

Does this still happen the same in INST mode?

(Assuming the callee hasn't SLOWed before it STOP/STPT's)

**Comment by Vermidia** [comment]
Yep(I tested both of them being inst)

**Comment by PuppyPi** [comment]
Beautiful, thanks!  :DD
