### ISSUE TITLE
MESG on OWNR

### ISSUE THREAD

**Issue by PuppyPi** [Creatures-Developer-Network/c2e-quirks#45]
MESG normally interrupts scripts like STPT (or like STOP?), right?
(https://github.com/Creatures-Developer-Network/c2e-quirks/issues/42)

So then what happens if you MESG on OWNR?  Does the script interrupt itself? XD
Or does it wait for it to finish before running the new event script?
Or does it wait for the whole CALL stack to finish before running the new event script?

**Comment by Vermidia** [comment]
The script interrupts itself, so OWNR never finishes running the next part of the script, if it has to wait or something.
If both scripts(the MESGed and the Current one) are inst, the Current one finishes and then the MESGed one runs, but if the Current one has to wait or execute over a number of ticks, the MESGed on will interrupt it first.

**Comment by PuppyPi** [comment]
Beautiful, thanks!  :D

It seems like a lot of these Agent VM things work not by directly changing the flow, but by setting some hidden variables in the agent which are only read on the start of the "do something for this agent for this tick" function X3
