### ISSUE TITLE
Infinity float literals?

### ISSUE THREAD

**Issue by PuppyPi** [Creatures-Developer-Network/c2e-quirks#46]
Are there infinity floating-point literals in CAOS like in some specs and languages?

Examples I've seen in the code world:
	inf
	+inf
	-inf
	minf  (Maxima)
	pinf  (I actually haven't seen this one but it could happen!)
	infinity
	+infinity
	-infinity
	∞  (haha nor this one, but it could happen too!)

But maybe it's something caosey and weird idk XD :3
INF_
INF!
+INF

**Comment by Vermidia** [comment]
There isn't any infinity floating-point literals.

**Comment by PuppyPi** [comment]
Thanks!  :>
