### ISSUE TITLE
No whitespace needed after literal

### ISSUE THREAD

**Issue by PuppyPi** [Creatures-Developer-Network/c2e-quirks#47]
https://creatures.wiki/CAOS_language_spec
	However, there is no need for whitespace directly after a string, bytestring or decimal.
	This may be a bug in CEE. It's present in openc2e too for compatibility reasons.

What about char literals?  Or were those included in "decimal"?  (And also binary literals?)

This would be good to add Test Cases for :3

And does this mean that either no caos command can start with e or d and be only numerals, or this just isn't true for such commands?
Because eg, if "E013" was a command, then 2.479E013 would be a float literal not 2.479 followed by the command E013

(And if infinity float literals exist in caos, I presume this doesn't apply to them?  Eg, if "inf" is the infinity float literal, then "setv ov00 infendm" wouldn't be valid caos, right? XD )
(https://github.com/Creatures-Developer-Network/c2e-quirks/issues/46)

**Comment by Vermidia** [comment]
Char literals don't seem to need whitespace after to call the next command.

For the other part, no idea, there aren't really any CAOS commands with e or d followed by only numbers.

**Comment by PuppyPi** [comment]
Thanks!
And there are no infinity literals like you confirmed, so that settles it I think :>

(I'll make a note that "E013" or etc. can never be a caos command XD )
