### ISSUE TITLE
NOT in conditions?

### ISSUE THREAD

**Issue by PuppyPi** [Creatures-Developer-Network/c2e-quirks#48]
Condition/Boolean/Logical "NOT" isn't a thing, right?  (as opposed to bitwise NOT, "NOTV")
And there's no way to do it in conditions that I'm just not aware of?

(I suppose it isn't strictly needed, since you can just perform the Duality transformation of boolean algebra on the condition and invert the (finite number of possible) leaf expressions and the return value, like = → <> and < → >= and etc.)

((Not that it matters much) but by that I mean, for example, "not ((a = b and c = d) or e = f)" → "(a <> b or c <> d) and e <> f" then swap the code inside the DOIF block with the ELSE block :> (it's more complicated if there's an ELIF))

**Comment by Vermidia** [comment]
There's ne/<> in CAOS

**Comment by Vermidia** [comment]
Oh you mean like and or or

**Comment by Vermidia** [comment]
No, you can't do doif not a eq b and c eq d, you'd have to do the ne/<> yeah

**Comment by PuppyPi** [comment]
Nice!  Thanks :>
