### ISSUE TITLE
Floating point literal syntax

### ISSUE THREAD

**Issue by PuppyPi** [Creatures-Developer-Network/c2e-quirks#49]
Is there a complete reference on the floating point syntax supported by caos?  :3

Eg, weird things sometimes supported by languages, like

NaN

-0
+0

.3
-.3
+.3

3.
-3.
+3.

2e3
0.2e3
2.0e3
.2e3
2.e3

2e+3
0.2e+3
2.0e+3
.2e+3
2.e+3

2e-3
0.2e-3
2.0e-3
.2e-3
2.e-3

2e+03
0.2e+03
2.0e+03
.2e+03
2.e+03

2e-03
0.2e-03
2.0e-03
.2e-03
2.e-03

and "E" and "d" and "D" in place of "e" above!

(I'm also largely putting this here so it gets turned into test cases someday XD )

**Comment by PuppyPi** [comment]
Oh and caos float literals might have a different syntax than the STOF function does!

**Comment by Vermidia** [comment]
NaN (From STOF) 0

-0 = 0
+0(From STOF) 0

.3 = 0.3
-.3 = -0.3
+.3(From STOF) 0.3

3. = 3.0

-3. = -3.0
+3.(From STOF) 3.0

2e3(From STOF) 2000.0
0.2e3(From STOF) 200.0
2.0e3(From STOF) 2000.0
.2e3(From STOF) 200.0
2.e3(From STOF) 2000.0

2e+3(From STOF) 2000.0
0.2e+3(From STOF) 200.0
2.0e+3(From STOF) 2000.0
.2e+3(From STOF) 200.0
2.e+3(From STOF) 2000.0

2e-3(From STOF) 0.002
0.2e-3(From STOF) 0.0002
2.0e-3(From STOF) 0.002
.2e-3(From STOF) 0.0002
2.e-3(From STOF) 0.002

The stuff after seems to give the same results
I used STOF when outv by itself didn't work, most STOF results have a few extra 0s I excluded
More STOF:
2E+03 = 2000.0
2d+03 = 2.0
2D+03 = 2.0

**Comment by PuppyPi** [comment]
Oh that's interesting!
So STOF just..stops parsing when it gets to an invalid character and returns what it has so far?

**Comment by Vermidia** [comment]
yes
outv stof "3randomtext" gives 3.0
outv stof "randomtext3" gives 0.0

**Comment by PuppyPi** [comment]
But outv 3randomtext or outv randomtext3 doesn't work, right?

What about outv 2d3?

Oh wait, does outv 2e3 not even work?!  :o
(You know that seems familiar to me!)

(I really need to fix my lc2e x'D )

**Comment by Vermidia** [comment]
![image](https://user-images.githubusercontent.com/32827189/119273303-dfa9be80-bbcf-11eb-80b1-6dae0479fec0.png)

**Comment by Vermidia** [comment]
I know floats from dbg: outv chem can come in a format that has e, but doesn't seem you can use the literal with e.

**Comment by PuppyPi** [comment]
Ahhhhhhhhhaha!
Well that makes parsing easier!
And it makes that thing about no caos commands named E013 or whatever not apply!  XD

Sweet!  :D
(I mean not sweet for people who want to use scientific notation directly as literals XD'   But nice for parsing and language formality!)


So then I think this is the formal syntax for caos float literals :3
(In pseudo-backus-naur form XD )

FloatLiteral  ::=  "-"?  {Base10Number | DecimalNDN | DecimalDN | DecimalND}
DecimalNDN  ::=  Base10Number  "."  Base10Number
DecimalDN  ::=  "."  Base10Number
DecimalND  ::=  Base10Number  "."
Base10Number  ::=  [0-9]+

Unless just a single period works as 0.0 in CAOS syntax too?  XD

Feel free to correct me, anyone!  :D

**Comment by Vermidia** [comment]
A single period is also invalid

**Comment by PuppyPi** [comment]
I suppose that does it!  :D

If anyone discovers anything else or that it's wrong, feel free to reopen!  :3
