### ISSUE TITLE
Exhaustive Message Numbers Lookup Table :>

### ISSUE THREAD

**Issue by PuppyPi** [Creatures-Developer-Network/c2e-quirks#51]
> The message_id is from the table of Message Numbers; remember that early Message Numbers differ slightly from Script Numbers.

So let's finally do it, the complete table XD
(I've always thought about this XD )

1.  Are message numbers _always_ just directly convertible to a event "script" number and otherwise it's exactly the same?
2.  What is that lookup table, exhaustively?  :>

Ie, is the engine equivalent to (if not literally) made with just a function somewhere like
```
int message_number_to_script_number(int n)
{
	if (n == 0)
		return 1;
	else if (n == 1):
		return 4;
	// ...
	else
		return n;
}
```

(except with the correct numbers XD )

Ie, there's a small exact finite set of message numbers that become different script numbers, and if it's not in that mapping, then it's just passed through unchanged?

**Comment by Vermidia** [comment]
The first 3 message numbers are off:
0 = Activate 1 (Deactivate Event Num)
1 = Activate 2 (Activate 1 Event Num)
2 = Deactivate (Activate 2 Event Num)
But every number after equals it's message number exactly as far as I'm aware

**Comment by PuppyPi** [comment]
So to convert a message number to a script number, it's

0 → 1
1 → 2
2 → 0

And all others are the same?  :>

(It's a 3-rotation! that's cute ^w^ )
(and good that it's bijective—phew! XD )

**Comment by Vermidia** [comment]
Message Ids only lists up to 14 specific ones, and the rest on there match up, and mesg writting 1000 = 1000 and stuff so I assume so.

**Comment by PuppyPi** [comment]
Perfect!  :D
