### ISSUE TITLE
Interleaved install script

### ISSUE THREAD

**Issue by PuppyPi** [Creatures-Developer-Network/c2e-quirks#57]
Can you interleave install script code amongst event scripts or does it have to all be at the beginning before the first SCRP?

**Comment by Vermidia** [comment]
Nope, has to be before the beginning of the scrp or CAOS Tool freaks out and won't inject. I assume this applies outside of it too.

**Comment by PuppyPi** [comment]
Good to know, thanks!
It'd be nice to know if the engine does that too (namely in bootstrap code) or if it's the injector tool itself doing that check.

**Comment by PuppyPi** [comment]
So since https://github.com/Creatures-Developer-Network/c2e-quirks/issues/58 is a thing, I guess interleaving raw code between event scripts and interleaving ISCR-ENDM bracketed code might be different in whether they're allowed and actually executed!

**Comment by Vermidia** [comment]
Sort of like #58 , the CAOS after a scrp seems to run, thought interestingly it doesn't require an iscr or endm.

```
scrp 3 0 0 1
endm
dbg: outs "Wa"
scrp 3 0 0 2
endm
dbg: outs "Ta"
```
will produce both the "Wa" and "Ta" just fine

**Comment by PuppyPi** [comment]
Okie dokie so it is like Python after all :3
Good to know, thanks!
