### ISSUE TITLE
Multiple ISCR's

### ISSUE THREAD

**Issue by PuppyPi** [Creatures-Developer-Network/c2e-quirks#58]
Can you have more than one?
Are they all just effectively concatenated?

**Comment by Vermidia** [comment]
CAOS Tool also won't inject with more than one either. Will do bootstrap testing.

**Comment by PuppyPi** [comment]
Thanks so much :)

**Comment by Vermidia** [comment]
Seems while CAOS Tool hates it, 
```iscr
dbg: outs "Hah"
endm

iscr
dbg: outs "Woah"
endm
```
is valid
Taking out the first endm breaks it, but taking out only the second doesn't.

**Comment by PuppyPi** [comment]
Oh really!

So to be sure it actually does execute both like they were concatenated into one iscr?

**Comment by Vermidia** [comment]
Yes, probably. It'll run the first one first than the second one, so I assume they could maybe be treated as separate install scripts.

**Comment by PuppyPi** [comment]
But it does run all of them (when install scripts are run), not just the first one, ignoring the ones after the first?

**Comment by Vermidia** [comment]
It does both yeah

**Comment by PuppyPi** [comment]
Sweet!  Thanks :>
