### ISSUE TITLE
EGG blocks in PRAY files. 

### ISSUE THREAD

**Issue by Kirtai** [Creatures-Developer-Network/c2e-quirks#6]
PRAY types are 4 ASCII  characters.
What's the fourth character in the "EGG" block type?
Space? Is anything else allowed?

**Comment by pushfoo** [comment]
might be a null, check egg files?

**Comment by pushfoo** [comment]
https://hexed.it/ can work if you don't want to install a hex editor or want one you can use anywhere

**Comment by Kirtai** [comment]
All the mall breed agents start with 
PRAY
EGGS
breedname.

Could be an error in the wiki.

**Comment by Kirtai** [comment]
Further testing shows that all breed agents I have use EGGS, not EGG to mark the block.
Error seems to be in the wiki documentation.

See [here](https://creatures.wiki/PRAY#EGG_blocks)
