### ISSUE TITLE
Multiple remove scripts

### ISSUE THREAD

**Issue by PuppyPi** [Creatures-Developer-Network/c2e-quirks#60]
Can there be more than one?

**Comment by Vermidia** [comment]
CAOS Tool also does not approve :P
Technically, yes but while this is valid:
```
rscr
dbg: outs "Bleh"
endm
rscr
dbg: outs "Removal"
```
when using ject "(caosfilename)" 1, only the first one will run, and it requires the endm.
Clarification: Only "Bleh" will be outputted to the debug monitor
```
rscr
dbg: outs "Bleh"
endm
rscr
dbg: outs "Removal"
rscr
dbg: outs "Umm"
```
Will also be valid, so it seems in this case(at least for JECT), it only will look for the first complete rscr-endm unless it's end of file probably, where it doesn't need the endm. Might wanna test that.

**Comment by PuppyPi** [comment]
Perfect, thanks so much!  :D
